<?php
/**
 * @file
 * Code for the gherkin_generator feature.
 */
define('GHERKIN_FOLDER', 'gherkin_features');

include_once 'gherkin_generator.features.inc';


function gherkin_generator_init() {
        drupal_add_js(array('gherkin_generator' => array('gherkinGeneratorDefaultPath' => GHERKIN_FOLDER)), 'setting');
}

function gherkin_generator_permission() {
    return array(
        'run gherkin test' =>  array(
            'title' => t('Allowed to run a gherkin test'),
        ),
        'save gherkin test' => array(
            'title' => t('Allowed to save tests to folders including generators')
        )
    );
}

function gherkin_generator_theme(){
    return array(
        'gherkin_results_area' => array(
            'variables' => array(
                'params' => NULL
            ),
            'template' => 'tpl/gherkin-results-area'
        ),
        'gherkin_questions_area' => array(
            'variables' => array(
                'params' => NULL
            ),
            'template' => 'tpl/gherkin-questions-area'
        )
    );
}

/**
 * @todo better way to get this info?
 */
function gherkin_generator_check_for_modules() {
    $module_array = array();
    $modules = module_list();
    foreach ($modules as $module) {
        if ($status = _gherkin_generator_has_folder($module)) {
            $module_array[$module] = $status;
        }
    }
    return $module_array;
}

function _gherkin_generator_has_folder($module) {
    $status = array();
    $path = drupal_get_path('module', $module);
    $full_path = $path . '/' . GHERKIN_FOLDER;
    if(drupal_realpath($full_path)) {
        $status['exists'] = TRUE;
        $status['writable'] = (is_writeable($full_path)) ? TRUE : FALSE;
        $nice_name = system_rebuild_module_data();
        $status['nice_name'] = $nice_name[$module]->info['name'];

        return $status;
    }
}

/**
 * @param $modules
 *  what modules have gherkin_folders
 *  from _gherkin_generator_has_folder()
 * @param $writable
 *  filter out writeable
 *
 * @return
 *  array of modules with folder
 */
function _gherkin_generator_options_list($module, $writable = TRUE) {
    $options = array();
    foreach($module as $key => $value) {
        $nice_name = $module[$key]['nice_name'];
        if($writable == TRUE) {
            ($module[$key]['writable'] == 1) ? $options[$key] = $nice_name : '';
        } else {
            $options[$key] = $nice_name;
        }
    }
    return $options;
}

function gherkin_generator_page_alter(&$page) {

    if(arg(2) == 'gherkin-generator' && arg(1) == 'add') {

        $page['content']['system_main']['#attributes']['class'][] = 'span6';
        $page['content']['test_results']['#theme'] = 'gherkin_results_area';
    }
}


function gherkin_generator_menu() {
    $items['admin/gherkin_generator/run'] = array(
        'page callback' => array('gherkin_generator_run'),
        'file' => 'inc/gherkin_generator_run.inc',
        'access arguments' => array('run gherkin test'),
        'type' => MENU_CALLBACK
    );
    $items['admin/gherkin_generator/save'] = array(
        'page callback' => array('gherkin_generator_save'),
        'file' => 'inc/gherkin_generator_save.inc',
        'access arguments' => array('run gherkin test'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function gherkin_generator_form_alter(&$form) {
    if($form['#form_id'] == 'gherkin_generator_node_form') {
        // move to it's own file to keep this fall shorter
        module_load_include('inc', 'gherkin_generator', 'inc/gherkin_generator_node_form');
        _gherkin_generator_node_form($form);
    }
}


function _gherkin_generator_save_to_file($request) {
    $feature = _gherkin_generator_parse_questions($request['scenario']);
    $filename = $request['filename'];
    $path = file_build_uri("/gherkin_tests/");

    if (!file_prepare_directory($path, FILE_CREATE_DIRECTORY)) {
        drupal_mkdir($path);
    }

    $response = file_unmanaged_save_data($feature, $path . '/' . $filename . '.feature', $replace = FILE_EXISTS_REPLACE);
    $file_url = l('click here', file_create_url($response), array('attributes' => array('target' => '_blank')));

    if($response == FALSE) {
        watchdog('gherkin_generator', "File could not be made.", $variables = array(), $severity = WATCHDOG_ERROR, $link = NULL);
        return array('message' => "Error file could not be save", 'file' => $response, 'error' => '1');
    } else {
        $date = format_date(time(), $type = 'medium', $format = '', $timezone = NULL, $langcode = NULL);
        watchdog('gherkin_generator', "%date File made %name", $variables = array('%date' => $date, '%name' => $response), $severity = WATCHDOG_NOTICE, $link = $file_url);
        return array('message' => t('@date: <br> File created !name to download ', array('@date' => $date, '!name' => $file_url)), 'file' => $response, 'error' => '0');
    }
}

/**
 * @todo this needs to not do count but text
 *   since a test can be numerous scenarios
 * @param $scenario
 * @return string
 */
function _gherkin_generator_parse_questions($scenario) {
    $final_output = '';
    $count = 0;
    foreach($scenario as $value) {
        if($count == 1) {
            $indent = '  ';
        } elseif($count > 1) {
            $indent = '    ';
        } else {
            $indent = '';
        }
        $final_output = $final_output .  $indent . $value . " \r\n";
        $count ++;
    }
    return $final_output;
}



