<?php
/**
 * @file
 * Code for the gherkin_generator feature.
 */
define('GHERKIN_FOLDER', 'gherkin_features');
define('GHERKIN_FILE_PREFIX', 'gherkin_generator');

include_once 'gherkin_generator.features.inc';
include_once 'gherkin_generator_helpers.inc';

function gherkin_generator_page_build(&$page) {
    drupal_add_js(array('gherkin_generator' => array('gherkinGeneratorDefaultPath' => file_directory_temp())), 'setting');
    drupal_add_js(array('gherkin_generator' => array('gherkinGeneratorFilePreix' => GHERKIN_FILE_PREFIX)), 'setting');
}

function gherkin_generator_permission() {
    return array(
        'run gherkin test' =>  array(
            'title' => t('Allowed to run a gherkin test'),
        ),
        'save gherkin test' => array(
            'title' => t('Allowed to save tests to folders including generators')
        )
    );
}

function gherkin_generator_menu() {
    $items['admin/gherkin_generator/run'] = array(
        'page callback' => array('gherkin_generator_run'),
        'file' => 'inc/gherkin_generator_run.inc',
        'access arguments' => array('run gherkin test'),
        'type' => MENU_CALLBACK
    );
    $items['admin/gherkin_generator/save'] = array(
        'page callback' => array('gherkin_generator_save'),
        'file' => 'inc/gherkin_generator_save.inc',
        'access arguments' => array('run gherkin test'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function gherkin_generator_library() {
    $path = drupal_get_path('module', 'gherkin_generator');
    $libraries['tag_it'] = array(
        'title' => 'jQuery Tagp-it',
        'website' => "http://aehlke.github.io/tag-it/",
        'version' => '2.0-x',
        'js' => array(
            $path . '/libraries/tag-it/js/tag-it.js' => array(),
        ),
        'css' => array(
            $path . '/libraries/tag-it/css/jquery.tagit.css' => array(
                'type' => 'file',
                'media' => 'screen'
            ),
            $path . '/libraries/tag-it/css/tagit.ui-zendesk.css' => array(
                'type' => 'file',
                'media' => 'screen'
            )
        )
    );
    return $libraries;
}

function gherkin_generator_theme(){
    return array(
        'gherkin_results_area' => array(
            'variables' => array(
                'params' => NULL
            ),
            'template' => 'tpl/gherkin-results-area',
            'file' => 'inc/gherkin_generator_theme_helpers.inc'
        ),
        'gherkin_questions_area' => array(
            'variables' => array(
                'params' => NULL
            ),
            'template' => 'tpl/gherkin-questions-area',
            'file' => 'inc/gherkin_generator_theme_helpers.inc'
        ),
        'gherkin_generator_create_file' => array(
            'variables' => array(
                'scenario' => NULL,
            ),
            'file' => 'inc/gherkin_generator_theme_helpers.inc'
        ),

        'gherkin_generator_create_html' => array(
            'variables' => array(
                'scenario' => NULL,
            ),
            'file' => 'inc/gherkin_generator_theme_helpers.inc'
        )
    );
}


/**
 * @todo better way to get this info?
 */
function gherkin_generator_check_for_modules() {
    if($cached = cache_get('gherkin_generator_modules', 'cache')) {
        return $cached->data;
    } else {
        $module_array = array();
        $modules = module_list();
        foreach ($modules as $module) {
            if ($status = _gherkin_generator_has_folder($module)) {
                $module_array[$module] = $status;
            }
        }
        cache_set('gherkin_generator_modules', $module_array, 'cache', CACHE_TEMPORARY);
        return $module_array;
    }
}



function gherkin_generator_page_alter(&$page) {

    if(arg(2) == 'gherkin-generator' && arg(1) == 'add') {

        $page['content']['system_main']['#attributes']['class'][] = 'span6';
        $page['content']['test_results']['#theme'] = 'gherkin_results_area';
    }
}



function gherkin_generator_form_alter(&$form) {
    if($form['#form_id'] == 'gherkin_generator_node_form') {
        // move to it's own file to keep this fall shorter
        drupal_add_library('gherkin_generator', 'tag_it') ;
        module_load_include('inc', 'gherkin_generator', 'inc/gherkin_generator_node_form');
        _gherkin_generator_node_form($form);
    }
}